plugins { id 'com.android.application' }
android {
 namespace 'com.leaden1.volumediagnostic'
 compileSdk 35
 defaultConfig { applicationId 'com.leaden1.volumediagnostic'; minSdk 23; targetSdk 35; versionCode 53; versionName '5.3' }
 buildTypes { release { minifyEnabled false; proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'),'proguard-rules.pro' } }
 compileOptions { sourceCompatibility JavaVersion.VERSION_17; targetCompatibility JavaVersion.VERSION_17 }
}
dependencies {
 implementation platform('org.jetbrains.kotlin:kotlin-bom:1.8.22')
 constraints {
  implementation('org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.8.22') { because('avoid duplicate class errors') }
  implementation('org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.8.22') { because('avoid duplicate class errors') }
 }
 implementation 'androidx.core:core:1.15.0'
 implementation 'androidx.media:media:1.7.0'
}
